[package]
name = "runtime"
version = "0.1.1"
authors = ["Kit Ewbank <Kit_Ewbank@hotmail.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
anyhow = "1.0.28"
wascc-codec = "0.5.2"
provider = { path = "../provider" }
wascc-host = { version = "0.5.3", features = ["manifest", "gantry"] }
wascc-log = { git = "https://github.com/wascc/logging-provider.git"}

[[bin]]
name = "bootstrap"
path = "src/main.rs"
