[package]
name = "aws-lambda-wascc-runtime"
version = "0.1.0"
authors = ["Kit Ewbank <Kit_Ewbank@hotmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
wascc-host = "0.5.0"
