[package]
name = "codec"
version = "0.6.0"
authors = ["Kit Ewbank <Kit_Ewbank@hotmail.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
serde = "1.0.105"
serde_derive = "1.0.105"
serde_json = "1.0.50"
serde_bytes = "0.11.3"
